### Basic operations

In [1]:
print('Hello World')

Hello World


In [2]:
import os
print(os.getcwd())
print(os.name)

/Users/mht/Desktop/Study Material/Python code /Python Code practice/GDrive Python
posix


In [3]:
import platform
print(platform.version())
print(platform.release())
print(platform.platform())

Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
21.1.0
macOS-10.16-x86_64-i386-64bit


In [4]:
print(7+4)
print(7-4)
print(7*4)
print(7/4)
print(7**2)

11
3
28
1.75
49


### Variables

In [5]:
x = 3
x

3

In [6]:
print(x)
print(type(x))
print(hex(id(x)))

3
<class 'int'>
0x106fe49a0


In [7]:
y = 3.15
y

3.15

In [8]:
print(y)
print(type(y))
print(hex(id(y)))

3.15
<class 'float'>
0x7fc72a73bd70


In [9]:
z = 'Hello'
z

'Hello'

In [10]:
print(z)
print(type(z))
print(hex(id(z)))

Hello
<class 'str'>
0x7fc72a7bd130


In [11]:
a = None
a

In [12]:
print(a)
print(type(a))
print(hex(id(a)))

None
<class 'NoneType'>
0x106fc1af8


In [13]:
b = True
b

True

In [14]:
print(b)
print(type(b))
print(hex(id(b)))

True
<class 'bool'>
0x106fae9b8


### Multipe Assignments and swaping of two numbers

In [15]:
p, q = 11, 9

In [16]:
print(p)
print(q)

11
9


In [17]:
p, q = q, p

In [18]:
print(p)
print(q)

9
11


### Data Structures in Python

In [19]:
first_tuple = (1,1.5,'Hello', True, None,(1,2,3))
first_tuple

(1, 1.5, 'Hello', True, None, (1, 2, 3))

In [21]:
print(first_tuple[1])
print(first_tuple[3])

1.5
True


In [23]:
print(first_tuple[0:3])
print(first_tuple[1:4])

(1, 1.5, 'Hello')
(1.5, 'Hello', True)


In [26]:
print(first_tuple[0:4:2])

(1, 'Hello')


In [24]:
#Reversing elements in tuple.
first_tuple[::-1]

((1, 2, 3), None, True, 'Hello', 1.5, 1)

In [25]:
first_tuple[::-2]

((1, 2, 3), True, 1.5)

#### List

In [48]:
first_list = [1,1.5,'Hello', True, None,(1,2,3)]
first_list

[1, 1.5, 'Hello', True, None, (1, 2, 3)]

In [28]:
print(first_list[1])
print(first_list[3])

1.5
True


In [29]:
print(first_list[0:3])
print(first_list[1:4])

[1, 1.5, 'Hello']
[1.5, 'Hello', True]


In [30]:
#Reversing elements in list.
first_list[::-1]

[(1, 2, 3), None, True, 'Hello', 1.5, 1]

In [31]:
first_list[::-2]

[(1, 2, 3), True, 1.5]

In [40]:
first_list.append(50)
first_list

[1, 1.5, 'Hello', True, None, (1, 2, 3), 50]

In [41]:
first_list.append([50, 1, 2])
first_list

[1, 1.5, 'Hello', True, None, (1, 2, 3), 50, [50, 1, 2]]

In [42]:
first_list.pop()

[50, 1, 2]

In [49]:
first_list

[1, 1.5, 'Hello', True, None, (1, 2, 3)]

In [50]:
first_list.insert(1, True)
first_list

[1, True, 1.5, 'Hello', True, None, (1, 2, 3)]

In [54]:
first_list.remove(True)
first_list

[True, None, (1, 2, 3)]

In [55]:
first_list.pop(1)
first_list

[True, (1, 2, 3)]

#### Sets

In [57]:
##Data in a set is uniquie and sorted.
e = {1,2,2,4,5,6,7,8,8}
e

{1, 2, 4, 5, 6, 7, 8}

In [59]:
#e[1] dispays an error

In [60]:
f = {2,2,5,6,6,9,9}
f

{2, 5, 6, 9}

In [61]:
#Union
e | f 

{1, 2, 4, 5, 6, 7, 8, 9}

In [62]:
#Intersection
e & f 

{2, 5, 6}

In [63]:
#Only elements in e.
e - f

{1, 4, 7, 8}

In [65]:
#Only elements in f.
f - e

{9}

#### Dictionary

In [67]:
first_dictionary = {'a':500, 'b':1000, 'c':1500}
first_dictionary

{'a': 500, 'b': 1000, 'c': 1500}

In [69]:
first_dictionary.keys()

dict_keys(['a', 'b', 'c'])

In [70]:
first_dictionary.values()

dict_values([500, 1000, 1500])

In [71]:
first_dictionary['a']

500

In [72]:
first_dictionary['d'] = 2000
first_dictionary

{'a': 500, 'b': 1000, 'c': 1500, 'd': 2000}

In [73]:
first_dictionary['c'] = 1400
first_dictionary

{'a': 500, 'b': 1000, 'c': 1400, 'd': 2000}

In [74]:
del first_dictionary['b']
first_dictionary

{'a': 500, 'c': 1400, 'd': 2000}

### Basic operations

In [77]:
#Concationation in tuple
g = (1,2,3)
f = (4,5,6)
g + f

(1, 2, 3, 4, 5, 6)

In [78]:
g * 2

(1, 2, 3, 1, 2, 3)

In [79]:
'Hello'+ ' '+'John'

'Hello John'

In [81]:
'Hello ' * 2

'Hello Hello '

### Functions

In [82]:
def first_function():
    print('Hello from first function')

In [84]:
first_function()

Hello from first function


In [85]:
def function_do_nothing():
    pass

In [86]:
function_do_nothing()

In [89]:
def fun_1(arg):
    print('Hello' + ' ' + arg)

In [90]:
fun_1('John')

Hello John


In [91]:
def area_rectangle(a,b):
    area = a * b
    print(area)

In [92]:
area_rectangle(2,2)

4


In [94]:
## error: 10 * area_rectangle(2,2)

In [95]:
def area_rectangle_1(a,b):
    area = a * b
    return area

In [96]:
area_rectangle_1(2,2)

4

In [97]:
10 * area_rectangle_1(2,2)

40

In [98]:
def calc_fun(a,b):
    return a + b, a - b, a / b

In [100]:
result = calc_fun(10,5)
result

(15, 5, 2.0)

In [101]:
type(result)

tuple

In [102]:
l, m , n = calc_fun(10,5)
print(l)
print(m)
print(n)

15
5
2.0


In [104]:
def vote_fun(age):
    if age >= 18:
        print('Can Vote')
    else:
        print('Not elegible')

In [107]:
vote_fun(21)

Can Vote


In [108]:
vote_fun(11)

Not elegible


In [110]:
def grade_fun(score):
    if score > 90:
        print('Grade A')
    elif score > 80:
        print('Grade B')
    elif score > 70:
        print('Grade C')
    elif score > 60:
        print('Grade D')
    else:
        print('Fail')

In [111]:
grade_fun(95)

Grade A


In [112]:
grade_fun(75)

Grade C


In [117]:
u = [1,2,3,4,5]
r = [1,2,3,4,5,6,7,8,9,10]

In [114]:
result = 0
for i in u:
    result += i
result

15

In [115]:
def sum_fun(b):
    result = 0
    for i in b:
        result += i
    return result

In [116]:
sum_fun(u)

15

In [118]:
sum_fun(r)

55

In [125]:
def div_fun(a,b):
    try:
        return a/b
    except ZeroDivisionError:
        print("Can't divide it by zero")
    except TypeError:
        print('Error!')

In [120]:
div_fun(10,5)

2.0

In [123]:
div_fun(10,0)

Can't divide it by zero


In [126]:
div_fun(10,'0')

Error!


In [127]:
w = [1,2,3,4,5,6]
p = [10,20,30,40,50,60]
q = [10,20,30,40,50,60,70]

In [129]:
for i, j in enumerate(q):
    print(i,j)

0 10
1 20
2 30
3 40
4 50
5 60
6 70


In [130]:
for i, j in zip(w,q):
    print(i * j)

10
40
90
160
250
360


In [134]:
for i, j in zip(w,p):
    print(i * j)

10
40
90
160
250
360


In [132]:
list(zip(w,p))

[(1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60)]

In [133]:
list(zip(w,q))

[(1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60)]

In [135]:
len(p)

6

In [144]:
h = 'hello123ABH@%^&*'
len(h)

16

In [145]:
sorted(h)

['%',
 '&',
 '*',
 '1',
 '2',
 '3',
 '@',
 'A',
 'B',
 'H',
 '^',
 'e',
 'h',
 'l',
 'l',
 'o']

In [147]:
sorted(p, reverse = True)

[60, 50, 40, 30, 20, 10]

In [149]:
list(reversed(p))

[60, 50, 40, 30, 20, 10]

### Numpy

In [150]:
import numpy as np

In [151]:
distance = [100,200,300]
time = [5, 2, 4]

In [158]:
# error: speed = distance/time

In [156]:
distance_array = np.array(distance)
time_array = np.array(time)
print(distance_array)
print(type(distance_array))
print(time_array)
print(type(time_array))

[100 200 300]
<class 'numpy.ndarray'>
[5 2 4]
<class 'numpy.ndarray'>


In [157]:
speed = distance_array/time_array
print(speed)
type(speed)

[ 20. 100.  75.]


numpy.ndarray

In [162]:
one_darray = np.array([1,2,3])
print(one_darray)
print(one_darray.ndim)
print(one_darray.shape)
print(one_darray.size)

[1 2 3]
1
(3,)
3


In [163]:
two_darray = np.array([[1,2,3],[4,5,6]])
print(two_darray)
print(two_darray.ndim)
print(two_darray.shape)
print(two_darray.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [178]:
three_darray = np.array([[[1,2,3],[4,5,6],[10,11,12]],[[7,8,9],[10,11,12],[13,14,15]]])
print(three_darray)
print(three_darray.ndim)
print(three_darray.shape)
print(three_darray.size)

[[[ 1  2  3]
  [ 4  5  6]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]
  [13 14 15]]]
3
(2, 3, 3)
18


In [165]:
for i in two_darray:
    print(i)

[1 2 3]
[4 5 6]


In [166]:
for val in two_darray:
    for i in val:
        print(i)

1
2
3
4
5
6


In [179]:
three_darray

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [180]:
three_darray[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [181]:
three_darray[0][0]

array([1, 2, 3])

In [182]:
three_darray[0][1]

array([4, 5, 6])

In [185]:
print(three_darray[0][:,0])
print(three_darray[0][:,1])
print(three_darray[0][:,0:2])
print(three_darray[0][0:2:,1:3])

[ 1  4 10]
[ 2  5 11]
[[ 1  2]
 [ 4  5]
 [10 11]]
[[2 3]
 [5 6]]


In [186]:
print(three_darray[1][:,0])
print(three_darray[1][:,1])
print(three_darray[1][:,0:2])
print(three_darray[1][0:2:,1:3])

[ 7 10 13]
[ 8 11 14]
[[ 7  8]
 [10 11]
 [13 14]]
[[ 8  9]
 [11 12]]


In [207]:
three_darray = np.array([[[1,2,3],[4,5,6],[10,11,12]],[[7,8,9],[10,11,12],[13,14,15]]])
three_darray

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [208]:
print(three_darray.max())
print(three_darray.argmax())

15
17


In [209]:
print(three_darray.mean())
print(three_darray.std())
print(three_darray.max())
print(three_darray.argmax())
print(three_darray.min())
print(three_darray.argmin())

8.5
4.112987559751022
15
17
1
0


In [211]:
#error: 
#print(three_darray.median())
#print(three_darray.mode())

In [212]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [213]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [215]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [216]:
np.full([3,3],5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [220]:
one_darray = np.array([1.1,2.6,3.9])
one_darray

array([1.1, 2.6, 3.9])

In [221]:
print(np.exp(one_darray))
print(np.cos(one_darray))
print(np.tan(one_darray))
print(np.floor(one_darray))
print(np.ceil(one_darray))

[ 3.00416602 13.46373804 49.40244911]
[ 0.45359612 -0.85688875 -0.7259323 ]
[ 1.96475966 -0.60159661  0.94742465]
[1. 2. 3.]
[2. 3. 4.]


In [240]:
#simple assignment
a = np.array([1,2,4])
b = a

In [241]:
print(b)
print(hex(id(b)))
print(a)
print(hex(id(a)))

[1 2 4]
0x7fc72d73af90
[1 2 4]
0x7fc72d73af90


In [244]:
#Shallow copy
c = a.view()
c

array([1, 2, 4])

In [245]:
c[0] = -1
print(c)
print(hex(id(c)))
print(a)
print(hex(id(a)))

[-1  2  4]
0x7fc72d49ce70
[-1  2  4]
0x7fc72d73af90


In [242]:
#Deep Copy
d = a.copy()
d

array([1, 2, 4])

In [243]:
d[0] = -1
print(d)
print(hex(id(d)))
print(a)
print(hex(id(a)))

[-1  2  4]
0x7fc72d73a2d0
[1 2 4]
0x7fc72d73af90


In [255]:
three_darray_1 = three_darray
three_darray_1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [254]:
three_darray_1.ravel()

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12,  7,  8,  9, 10, 11, 12, 13, 14,
       15])

In [259]:
f = three_darray_1.flatten()
f.size

18

In [264]:
f.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [265]:
f

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 11],
       [12,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [266]:
f.resize(6,3)
f

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [267]:
np.split(f,6)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[10, 11, 12]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]])]

In [273]:
#Error: np.split(f,6).ndim

In [268]:
np.stack([f,f])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [269]:
np.stack([f,f]).ndim

3

In [270]:
np.hstack([f,f])

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [10, 11, 12, 10, 11, 12],
       [ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12],
       [13, 14, 15, 13, 14, 15]])

In [271]:
np.hstack([f,f]).ndim

2

In [275]:
np.hsplit(f,3)

[array([[ 1],
        [ 4],
        [10],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [11],
        [ 8],
        [11],
        [14]]),
 array([[ 3],
        [ 6],
        [12],
        [ 9],
        [12],
        [15]])]

In [277]:
# Error: np.split(f,6).ndim

In [279]:
a = np.array([1,2,3])
b = np.array([3,4,5])
c = np.array([1,2,3,5])

In [280]:
a * b

array([ 3,  8, 15])

In [282]:
#Broadcast Error:
#a * c

In [283]:
5 * a

array([ 5, 10, 15])

In [287]:
A = two_darray[:,0:2]
A

array([[1, 2],
       [4, 5]])

In [290]:
Y = np.array([3,6])
Y

array([3, 6])

In [288]:
np.transpose(A)

array([[1, 4],
       [2, 5]])

In [289]:
A.T

array([[1, 4],
       [2, 5]])

In [291]:
np.linalg.det(A)

-2.9999999999999996

In [292]:
np.linalg.inv(A)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [293]:
np.dot(A,np.linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

In [297]:
np.dot(np.linalg.inv(A),Y)

array([-1.,  2.])

In [296]:
np.linalg.solve(A,Y)

array([-1.,  2.])

In [298]:
np.linalg.eig(A)

(array([-0.46410162,  6.46410162]),
 array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

In [301]:
np.linalg.eigvals(A)

array([-0.46410162,  6.46410162])

In [302]:
np.linalg.eigvals(A)

array([-1.47213595,  7.47213595])

### SciPy

In [303]:
from scipy.integrate import quad

In [320]:
def fun_1(x):
    return x**2

In [321]:
quad(fun_1, 1,2)

(2.3333333333333335, 2.590520390792032e-14)

In [322]:
def fun_2(x,a,b):
    return x**a + b**x

In [323]:
quad(fun_2,1,2, args = (1,2))

(4.385390081777926, 4.8687610407526515e-14)

In [313]:
from scipy.integrate import dblquad

In [324]:
def fun_3(x,y,a,b):
    return x**a + y**b

In [325]:
dblquad(fun_3,1,2,1,2, args = (2,2))

(4.666666666666666, 7.021774688857003e-14)

In [327]:
def fun_4(x,y,a,b):
    return x**a + b**y

In [328]:
dblquad(fun_4,1,2,1,2, args = (2,2))

(5.218723415111261, 7.024733474226173e-14)

In [329]:
from scipy.optimize import minimize
from scipy.optimize import root

In [330]:
minimize(fun_1,1)

      fun: 5.5507930986288555e-17
 hess_inv: array([[0.5]])
      jac: array([4.32220232e-13])
  message: 'Optimization terminated successfully.'
     nfev: 9
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([-7.45036449e-09])

In [331]:
minimize(fun_1,1).fun

5.5507930986288555e-17

In [336]:
root(fun_1,1)

    fjac: array([[-1.]])
     fun: array([3.22743727e-167])
 message: 'The number of calls to function has reached maxfev = 400.'
    nfev: 400
     qtf: array([-8.44954046e-167])
       r: array([-2.40653302e-83])
  status: 2
 success: False
       x: array([5.68105383e-84])

In [332]:
root(fun_1,1).x

array([5.68105383e-84])

In [333]:
def fun_6(x,a):
    return x**a + 1

In [334]:
minimize(fun_6,1, args = 3).fun

-3.247372710752487e+24

In [335]:
root(fun_6,1, args = 3).x

array([-1.])

In [337]:
from scipy import linalg

In [338]:
A

array([[1, 2],
       [4, 5]])

In [339]:
print(linalg.det(A))
print(linalg.inv(A))

-3.0
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [341]:
np.dot(A,linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

In [343]:
linalg.solve(A,Y)

array([-1.,  2.])

In [344]:
np.dot(linalg.inv(A),Y)

array([-1.,  2.])

In [347]:
from scipy.stats import norm

In [351]:
norm.rvs(size = 10, loc = 0, scale = 1)

array([-0.5320745 , -0.6806516 ,  1.21823217, -0.17204955, -1.54255267,
       -1.16027322, -1.21505985, -0.0752587 ,  0.32507574,  0.16215686])

In [355]:
norm.pdf(1.5, loc = 0, scale = 1)

0.12951759566589174

In [354]:
norm.cdf(1.5, loc = 0, scale = 1)

0.9331927987311419

### Pandas

#### Series

#### DataFrame

In [357]:
import numpy as np
import pandas as pd

In [429]:
movie_ratings = pd.DataFrame({'movie1':[5,4,3,3,2,1],
                              'movie2':[4,5,2,3,4,2],
                             'Name':list('xyzmno')},
                             index = list('abcdef'))
movie_ratings

movie1  movie2 Name
a       5       4    x
b       4       5    y
c       3       2    z
d       3       3    m
e       2       4    n
f       1       2    o

In [362]:
def movie_rat(rating):
    if rating == 5:
        return 'A'
    elif rating == 4:
        return 'B'
    elif rating == 3:
        return 'C'
    elif rating == 2:
        return 'D'
    else:
        return 'E'

In [372]:
movie_ratings[['movie1','movie2']].applymap(movie_rat)

movie1 movie2
a      A      B
b      B      A
c      C      D
d      C      C
e      D      B
f      E      D

In [430]:
movie_ratings

movie1  movie2 Name
a       5       4    x
b       4       5    y
c       3       2    z
d       3       3    m
e       2       4    n
f       1       2    o

In [431]:
movie_ratings.drop(['Name'], axis = 1, inplace = True)
movie_ratings

movie1  movie2
a       5       4
b       4       5
c       3       2
d       3       3
e       2       4
f       1       2

In [405]:
sales_data = pd.DataFrame({'prod_id':[101,102,103,104,105,106,107,108,109,110],
                     'year':[2017,2018,2017,2018,2017,2018,2017,2018,2017,2018],
                     'sales':[192,321,456,383,100,898,999,125,665,330]})
sales_data

prod_id  year  sales
0      101  2017    192
1      102  2018    321
2      103  2017    456
3      104  2018    383
4      105  2017    100
5      106  2018    898
6      107  2017    999
7      108  2018    125
8      109  2017    665
9      110  2018    330

In [406]:
sales_data['prod_id']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: prod_id, dtype: int64

In [407]:
sales_data.prod_id

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: prod_id, dtype: int64

In [408]:
sales_data[['prod_id','sales']]

prod_id  sales
0      101    192
1      102    321
2      103    456
3      104    383
4      105    100
5      106    898
6      107    999
7      108    125
8      109    665
9      110    330

In [409]:
sales_data.prod_id = sales_data.prod_id.astype('str')

In [410]:
sales_data.head()

prod_id  year  sales
0     101  2017    192
1     102  2018    321
2     103  2017    456
3     104  2018    383
4     105  2017    100

In [411]:
sales_data.tail()

prod_id  year  sales
5     106  2018    898
6     107  2017    999
7     108  2018    125
8     109  2017    665
9     110  2018    330

In [412]:
sales_data.describe()

year       sales
count    10.000000   10.000000
mean   2017.500000  446.900000
std       0.527046  312.425796
min    2017.000000  100.000000
25%    2017.000000  224.250000
50%    2017.500000  356.500000
75%    2018.000000  612.750000
max    2018.000000  999.000000

In [413]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   prod_id  10 non-null     object
 1   year     10 non-null     int64 
 2   sales    10 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes


In [414]:
print(sales_data['sales'].mean())
print(sales_data['sales'].median())
print(sales_data['sales'].mode())
print(sales_data['sales'].count())
print(sales_data['sales'].sum())
print(sales_data['sales'].max())
print(sales_data['sales'].min())
print(sales_data['sales'].std())

446.9
356.5
0    100
1    125
2    192
3    321
4    330
5    383
6    456
7    665
8    898
9    999
dtype: int64
10
4469
999
100
312.42579563438386


In [415]:
sales_data.groupby(['year']).sales.sum()

year
2017    2412
2018    2057
Name: sales, dtype: int64

In [416]:
sales_data.groupby(['year']).sales.mean()

year
2017    482.4
2018    411.4
Name: sales, dtype: float64

In [417]:
sales_data.groupby(['year']).sales.count()

year
2017    5
2018    5
Name: sales, dtype: int64

In [423]:
sales_data.sort_values('sales', ascending = False, inplace = True)
sales_data.reset_index(drop = True)

prod_id  year  sales
0     107  2017    999
1     106  2018    898
2     109  2017    665
3     103  2017    456
4     104  2018    383
5     110  2018    330
6     102  2018    321
7     101  2017    192
8     108  2018    125
9     105  2017    100

In [424]:
sales_data['year'].value_counts()

2017    5
2018    5
Name: year, dtype: int64