In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a[::-1]

array([5, 4, 3, 2, 1])

In [5]:
a[1:4]

array([2, 3, 4])

In [7]:
b = np.array([[[10,11,12],[13,1,15]],[[20,21,22],[23,1,25]]])
b

array([[[10, 11, 12],
        [13,  1, 15]],

       [[20, 21, 22],
        [23,  1, 25]]])

In [8]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)

3
12
(2, 2, 3)
int64


In [10]:
b[0]

array([[10, 11, 12],
       [13,  1, 15]])

In [14]:
b[0][:,0:2]

array([[10, 11],
       [13,  1]])